# Reading Secret data from Repository

name: Repository Secret Data

# Controls when the workflow will run
on: push
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  secretdata:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{secrets.USERNAME}}
          echo ${{secrets.PASSWORD}}
