 History
 1 contributor
31 lines (22 sloc)  619 Bytes

# To understand user defined variables

name: User Defined Variable Demo

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
env:
 firstName: Gerard
 lastName: Torres
 
jobs:
 windows-job:
   runs-on: windows-latest
   steps:
     - name: Display First Name variable
       run: echo "Hi ${{env.firstName}}"
     - name: Display Last Name Variable
       run: echo "Hi ${{env.lastName}}"
     - name: Display Job
       run: echo "${{job}}}
       env:
        job: "Developer"
     
 ubuntu-job:
   runs-on: ubuntu-latest
   steps:
     - name: Display env variables
       run: echo "Hi ${{env.lastName}}"
